In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df = pd.read_csv('.\data\premium.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1333 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [48]:
#bmi의 널처리
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [49]:
from sklearn.preprocessing import LabelEncoder

In [50]:
# 문자열 데이터의 수치화 > LabelEncoder
col_list = ['sex', 'smoker', 'region']
for col in col_list:
  enc = LabelEncoder()
  df[col] = enc.fit_transform(df[col])

df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [51]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [52]:
# 스케일링 하기

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, random_state=42)

In [53]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [54]:
# 연속형 컬럼
num_cols = ['bmi']

scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

display(X_train[num_cols].describe().round(4))

             bmi
count  1070.0000
mean      0.0000
std       1.0005
min      -2.4246
25%      -0.7201
50%      -0.0506
75%       0.6439
max       3.7506

In [61]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [62]:
# 선형회귀 모델
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
mae, mse, rmse, r2

(4172.783193083617,
 33640928.3211508,
 np.float64(5800.0800271333155),
 0.7833094802263592)

# 다항회귀

In [63]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

In [70]:
degree = [2, 3, 4]

for deg in degree:
  model_poly = Pipeline([('poly', PolynomialFeatures(degree=deg, include_bias=False)),
                         ('linear', LinearRegression())])
  model_poly.fit(X_train, y_train)
  poly_pred = model_poly.predict(X_test)

  mae = mean_absolute_error(y_test, poly_pred)
  mse = mean_squared_error(y_test, poly_pred)
  rmse = np.sqrt(mse)
  r2 = r2_score(y_test, poly_pred)
mae, mse, rmse, r2

(3120.6620650772716,
 34379524.83832539,
 np.float64(5863.405566590579),
 0.778551975864955)

In [66]:
from sklearn.ensemble import RandomForestRegressor
model_rf = RandomForestRegressor(n_estimators=100, random_state=0)
model_rf.fit(X_train,y_train)
y_pred_rf = model_rf.predict(X_test)
mae = mean_absolute_error(y_test, y_pred_rf)
mse = mean_squared_error(y_test, y_pred_rf)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_rf)
mae, mse, rmse, r2

(2499.0538510119104,
 21474275.29598436,
 np.float64(4634.034451316084),
 0.861678255985478)

In [67]:
# 특성 중요도
import pandas as pd
feature_names = ['age', 'sex', 'bmi', 'children', 'smoker', 'region']
importance_df = pd.DataFrame({
  'feature': feature_names,
  'importance': model_rf.feature_importances_
}).sort_values('importance', ascending=False)

print(f'특성중요도 \n-------------------------------------\n {importance_df}')

특성중요도
-------------------------------------
     feature  importance
4    smoker    0.610743
2       bmi    0.207945
0       age    0.136268
3  children    0.022684
5    region    0.015433
1       sex    0.006929

# XGBRegressor

In [68]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# 모델 생성
model_xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=0,
    objective='reg:squarederror'
)

# 학습
model_xgb.fit(X_train, y_train)

# 예측
y_pred_xgb = model_xgb.predict(X_test)

# 평가
mae = mean_absolute_error(y_test, y_pred_xgb)
mse = mean_squared_error(y_test, y_pred_xgb)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_xgb)

mae, mse, rmse, r2

(2530.7423597910442,
 20312524.064407628,
 np.float64(4506.941764035522),
 0.8691614168487813)

In [69]:
import optuna
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 5),
        'random_state': 0
    }
    model = RandomForestRegressor(**params)
    score = -cross_val_score(model, X, y, cv=5, scoring='neg_mean_absolute_error').mean()
    return score

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50)

print(f'Best MAE : {round(study.best_value, 4)}')
print(f'Best Params : {study.best_params}')

[I 2026-02-27 17:25:42,094] A new study created in memory with name: no-name-7ffad9cd-b74a-47c9-9924-9bbb46b252b6
[I 2026-02-27 17:25:43,797] Trial 0 finished with value: 2571.045056871232 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 0 with value: 2571.045056871232.
[I 2026-02-27 17:25:44,234] Trial 1 finished with value: 2560.8058359901993 and parameters: {'n_estimators': 60, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 1 with value: 2560.8058359901993.
[I 2026-02-27 17:25:45,335] Trial 2 finished with value: 2552.2630387809013 and parameters: {'n_estimators': 212, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 2 with value: 2552.2630387809013.
[I 2026-02-27 17:25:46,764] Trial 3 finished with value: 2527.1802514899746 and parameters: {'n_estimators': 247, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 3 with value: 2527.1802514899746.
[I 2026-02-27 17:25:48,018] Trial 4 finished with value: 2684.6256053006678 and parameters: {'n_estimators': 291, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 3 with value: 2527.1802514899746.
[I 2026-02-27 17:25:49,860] Trial 5 finished with value: 2679.4238623998494 and parameters: {'n_estimators': 250, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 3 with value: 2527.1802514899746.
[I 2026-02-27 17:25:50,324] Trial 6 finished with value: 2586.1762977113417 and parameters: {'n_estimators': 62, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 3 with value: 2527.1802514899746.
[I 2026-02-27 17:25:50,707] Trial 7 finished with value: 2677.1148197455814 and parameters: {'n_estimators': 86, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 3 with value: 2527.1802514899746.
[I 2026-02-27 17:25:52,337] Trial 8 finished with value: 2552.1587860895434 and parameters: {'n_estimators': 262, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 3 with value: 2527.1802514899746.
[I 2026-02-27 17:25:52,804] Trial 9 finished with value: 2527.031525822778 and parameters: {'n_estimators': 70, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 9 with value: 2527.031525822778.
[I 2026-02-27 17:25:53,698] Trial 10 finished with value: 2529.6946172763846 and parameters: {'n_estimators': 136, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 9 with value: 2527.031525822778.
[I 2026-02-27 17:25:54,762] Trial 11 finished with value: 2535.6963326734135 and parameters: {'n_estimators': 163, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 9 with value: 2527.031525822778.
[I 2026-02-27 17:25:55,542] Trial 12 finished with value: 2535.6704335701634 and parameters: {'n_estimators': 120, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 9 with value: 2527.031525822778.
[I 2026-02-27 17:25:56,859] Trial 13 finished with value: 2556.1617121131017 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 9 with value: 2527.031525822778.
[I 2026-02-27 17:25:58,034] Trial 14 finished with value: 2516.6691816444213 and parameters: {'n_estimators': 224, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:25:59,437] Trial 15 finished with value: 2555.1686331752844 and parameters: {'n_estimators': 207, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:00,548] Trial 16 finished with value: 2562.3084549180594 and parameters: {'n_estimators': 169, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:01,290] Trial 17 finished with value: 2531.4310813744946 and parameters: {'n_estimators': 111, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:02,018] Trial 18 finished with value: 2538.259840447453 and parameters: {'n_estimators': 148, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:03,546] Trial 19 finished with value: 2569.4251048497767 and parameters: {'n_estimators': 228, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:04,732] Trial 20 finished with value: 2540.992430555805 and parameters: {'n_estimators': 185, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:06,137] Trial 21 finished with value: 2527.724340386302 and parameters: {'n_estimators': 245, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:07,541] Trial 22 finished with value: 2517.662393587171 and parameters: {'n_estimators': 265, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:08,880] Trial 23 finished with value: 2542.764668049527 and parameters: {'n_estimators': 275, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 14 with value: 2516.6691816444213.
[I 2026-02-27 17:26:10,037] Trial 24 finished with value: 2505.571937925673 and parameters: {'n_estimators': 220, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 24 with value: 2505.571937925673.
[I 2026-02-27 17:26:11,493] Trial 25 finished with value: 2505.872134142369 and parameters: {'n_estimators': 275, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 24 with value: 2505.571937925673.
[I 2026-02-27 17:26:12,698] Trial 26 finished with value: 2504.813712833166 and parameters: {'n_estimators': 229, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 26 with value: 2504.813712833166.
[I 2026-02-27 17:26:14,423] Trial 27 finished with value: 2538.380269336181 and parameters: {'n_estimators': 281, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 26 with value: 2504.813712833166.
[I 2026-02-27 17:26:15,546] Trial 28 finished with value: 2534.1179930279045 and parameters: {'n_estimators': 231, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 26 with value: 2504.813712833166.
[I 2026-02-27 17:26:17,232] Trial 29 finished with value: 2517.668961669926 and parameters: {'n_estimators': 296, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 26 with value: 2504.813712833166.
[I 2026-02-27 17:26:18,452] Trial 30 finished with value: 2542.0625952671007 and parameters: {'n_estimators': 193, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 26 with value: 2504.813712833166.
[I 2026-02-27 17:26:19,707] Trial 31 finished with value: 2504.4150145465032 and parameters: {'n_estimators': 225, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:20,874] Trial 32 finished with value: 2504.474474299561 and parameters: {'n_estimators': 219, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:21,839] Trial 33 finished with value: 2684.2482062081453 and parameters: {'n_estimators': 215, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:22,977] Trial 34 finished with value: 2534.948215477367 and parameters: {'n_estimators': 237, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:24,116] Trial 35 finished with value: 2515.734449300312 and parameters: {'n_estimators': 181, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:25,304] Trial 36 finished with value: 2521.625234962347 and parameters: {'n_estimators': 213, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:26,920] Trial 37 finished with value: 2550.1602100162477 and parameters: {'n_estimators': 250, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:27,787] Trial 38 finished with value: 2687.1005513719706 and parameters: {'n_estimators': 196, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:28,957] Trial 39 finished with value: 2516.3719951318913 and parameters: {'n_estimators': 220, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:30,538] Trial 40 finished with value: 2541.5218464270474 and parameters: {'n_estimators': 259, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:31,829] Trial 41 finished with value: 2505.900405356982 and parameters: {'n_estimators': 239, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:33,343] Trial 42 finished with value: 2506.303198880134 and parameters: {'n_estimators': 271, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:34,759] Trial 43 finished with value: 2534.7449956507107 and parameters: {'n_estimators': 287, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:36,242] Trial 44 finished with value: 2517.5026780157227 and parameters: {'n_estimators': 258, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:37,163] Trial 45 finished with value: 2686.1749568014175 and parameters: {'n_estimators': 207, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:38,386] Trial 46 finished with value: 2535.1315896997776 and parameters: {'n_estimators': 248, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:39,582] Trial 47 finished with value: 2516.6088966807206 and parameters: {'n_estimators': 225, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:41,439] Trial 48 finished with value: 2597.340386747515 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 31 with value: 2504.4150145465032.
[I 2026-02-27 17:26:42,688] Trial 49 finished with value: 2551.3558246031703 and parameters: {'n_estimators': 191, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 31 with value: 2504.4150145465032.

Best MAE : 2504.415
Best Params : {'n_estimators': 225, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3}